In [ ]:
import pandas as pd

In [ ]:
ds=pd.read_csv('/content/Data_Viz_Challenge_2025-UCB_Trees.csv')

In [ ]:
ds

,OBJECTID,Tree ID,Tree Type,Genus,Species,Cultivar or Varietal,Common Name,Canopy Spread,Height,Latitude,Longitude
0,1,10146,DECIDUOUS,Quercus,bicolor,NaN,Swamp White Oak,19.0,21.0,40.009104,-105.272529
1,2,10150,DECIDUOUS,Gymnocladus,dioicus,NaN,Kentucky Coffeetree,31.0,47.0,40.009136,-105.272797
2,3,10041,DECIDUOUS,Quercus,rubra,NaN,Northern Red Oak,65.0,102.0,40.008888,-105.274886
3,4,10042,DECIDUOUS,Quercus,rubra,NaN,Northern Red Oak,42.0,54.0,40.008775,-105.275000
4,5,10051,DECIDUOUS,Crataegus,NaN,NaN,Hawthorne,18.0,20.0,40.008870,-105.275428
...,...,...,...,...,...,...,...,...,...,...,...
772,773,13830,DECIDUOUS,Taxodium,NaN,NaN,Bald Cypress,15.0,25.0,40.010252,-105.273964
773,774,13833,DECIDUOUS,Crataegus,NaN,NaN,Hawthorne,15.0,20.0,40.010316,-105.274258
774,775,14027,DECIDUOUS,Catalpa,speciosa,NaN,Western Catalpa,5.0,10.0,40.008315,-105.272798
775,776,15693,DECIDUOUS,Acer,saccharum,Caddo,NaN,NaN,NaN,40.009700,-105.274889
776,777,15694,DECIDUOUS,Acer,saccharum,Caddo,Sugar Maple,NaN,12.0,40.009862,-105.275143

In [ ]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   OBJECTID              777 non-null    int64
 1   Tree ID               777 non-null    int64
 2   Tree Type             777 non-null    object
 3   Genus                 777 non-null    object
 4   Species               581 non-null    object
 5   Cultivar or Varietal  7 non-null      object
 6   Common Name           776 non-null    object
 7   Canopy Spread         773 non-null    float64
 8   Height                776 non-null    float64
 9   Latitude              777 non-null    float64
 10  Longitude             777 non-null    float64
dtypes: float64(4), int64(2), object(5)
memory usage: 66.9+ KB

In [ ]:
# Fill missing species names with 'Unknown'
ds['Species'].fillna('Unknown', inplace=True)

<ipython-input-20-1ad28f000b16>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds['Species'].fillna('Unknown', inplace=True)

In [ ]:
# Fill missing common names with 'Unknown'
ds['Common Name'].fillna('Unknown', inplace=True)

<ipython-input-21-336737864e17>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds['Common Name'].fillna('Unknown', inplace=True)

In [ ]:
# Fill missing Canopy Spread and Height with median values (to maintain realistic values)
ds['Canopy Spread'].fillna(ds['Canopy Spread'].median(), inplace=True)

<ipython-input-22-43f1cb7eae66>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds['Canopy Spread'].fillna(ds['Canopy Spread'].median(), inplace=True)

In [ ]:
ds['Height'].fillna(ds['Height'].median(), inplace=True)

<ipython-input-23-e9669016850b>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds['Height'].fillna(ds['Height'].median(), inplace=True)

In [ ]:
# Ensure data types are correct
ds['Tree ID'] = ds['Tree ID'].astype(str)  # Treat Tree ID as a string to avoid unnecessary calculations

In [ ]:
ds

,OBJECTID,Tree ID,Tree Type,Genus,Species,Cultivar or Varietal,Common Name,Canopy Spread,Height,Latitude,Longitude
0,1,10146,DECIDUOUS,Quercus,bicolor,NaN,Swamp White Oak,19.0,21.0,40.009104,-105.272529
1,2,10150,DECIDUOUS,Gymnocladus,dioicus,NaN,Kentucky Coffeetree,31.0,47.0,40.009136,-105.272797
2,3,10041,DECIDUOUS,Quercus,rubra,NaN,Northern Red Oak,65.0,102.0,40.008888,-105.274886
3,4,10042,DECIDUOUS,Quercus,rubra,NaN,Northern Red Oak,42.0,54.0,40.008775,-105.275000
4,5,10051,DECIDUOUS,Crataegus,Unknown,NaN,Hawthorne,18.0,20.0,40.008870,-105.275428
...,...,...,...,...,...,...,...,...,...,...,...
772,773,13830,DECIDUOUS,Taxodium,Unknown,NaN,Bald Cypress,15.0,25.0,40.010252,-105.273964
773,774,13833,DECIDUOUS,Crataegus,Unknown,NaN,Hawthorne,15.0,20.0,40.010316,-105.274258
774,775,14027,DECIDUOUS,Catalpa,speciosa,NaN,Western Catalpa,5.0,10.0,40.008315,-105.272798
775,776,15693,DECIDUOUS,Acer,saccharum,Caddo,Unknown,16.0,35.0,40.009700,-105.274889
776,777,15694,DECIDUOUS,Acer,saccharum,Caddo,Sugar Maple,16.0,12.0,40.009862,-105.275143

In [ ]:
# Save cleaned dataset for Tableau
cleaned_file_path = "Data_Viz_Challenge_2025-UCB_Trees_Cleaned.csv"
ds.to_csv(cleaned_file_path, index=False)

print(f"Cleaned dataset saved as: {cleaned_file_path}")

Cleaned dataset saved as: Data_Viz_Challenge_2025-UCB_Trees_Cleaned.csv